apiVersion: v1
name: digest-mailer
description: Buildinglink digest email service
type: application
version: 0.1.5
appVersion: 1.0.0
icon: file://../logo.png
keywords:
  - buildinglink
  - mailers
maintainers:
  - name: buildinglink  
    email: charts@buildinglink.com

